src/js/menu.js

Allows user to Cmd+Q from Welcome view to quit the app.
Only tested on macOS.

Support "Quit" and "About" from Menu in Welcome view

---

src/css/toolbar.css
src/js/window/toolbar.js

- center toolbar
- drop palette down to be more vertically aligned with the other buttons
- more breathing room for the palette
- ditch separator lines

Toolbar refinements

---

src/js/window/main-window.js
src/js/window/storyboarder-sketch-pane.js
src/main-window.html

Added move/scale modes back into the app.
Related:
- https://github.com/wonderunit/storyboarder/issues/161
- https://github.com/wonderunit/storyboarder/issues/243
- https://github.com/wonderunit/storyboarder/issues/244
Could use a refactoring pass. Very messy. Lots of code duplication in the strategies. Calls to `emit` that probably should be method calls.
Known Issues:
- https://github.com/wonderunit/storyboarder/issues/245
- https://github.com/wonderunit/storyboarder/issues/246
- https://github.com/wonderunit/storyboarder/issues/247

Add Move and Scale modes

---

src/js/main.js
src/js/menu.js
src/js/window/main-window.js
src/js/window/onion-skin.js
src/js/window/storyboarder-sketch-pane.js
src/js/window/toolbar.js
src/main-window.html

See https://github.com/wonderunit/storyboarder/issues/31
**TASKS**

Onion Skin

---

README.md

To show which key or keys to press to achieve something in an APG design pattern, we use the `<kbd>` element like so: `<kbd>ctrl</kbd>+<kbd>Page Up</kbd>`.

Simplify key commands using kbd tag

---

src/js/files/FileReader.js
src/js/main.js
src/js/menu.js
src/js/window/main-window.js

This is a basic implementation of importing files. When you select "Import Storyboards" from the file menu (or invoke the Shift+Apple+I shortcut) you'll be presented with a file system dialog where you can select jpgs, pngs, or folders. We then add storyboards for each of the files, traversing directories recursively. During import, we resize the image to fit into the current storyboard dimensions, copy it to a new file in the images folder, generate a thumbnail, and finally save the board file.

Importing Images

---

src/js/files/FileReader.js
src/js/main.js

Photoshop files are made available in the file selector, and will import along with the pngs and jpegs. There are some cases when this will fail due to limitations on the photoshop file reading library—the one I ran into during testing is trying to open a 16bit photoshop file. For now, it fails silently, and sends an error log to the console.

Added support for photoshop importing.

---

src/js/files/FileReader.js
src/js/prefs.js
src/js/window/main-window.js

Fixes #325.
Added support for targeting different layers on importing.
Make the thumbnail convas the correct size, then draw the image into it at its correct size.
Note that we currently read from the preference object, but the UI to update it isn't set up.

Import to reference layer.

---

src/css/mainwindow.css
src/js/utils/index.js
src/js/window/main-window.js
src/js/window/storyboarder-sketch-pane.js

Fixes #335
If we wanted to 100% reflect the state of batch vs single mode, we could also:
- disable ‘clear’ buttons
- disable light layer buttons
- disable light layer slider
- disable show in finder
- disable open in editor
- maybe change the top text to reflect that we’re in multi-select mode
- reset new shot
- reset dialogue msecs
Holding off on that for now

User can Batch Edit Properties in a Selection of Boards

---

src/js/window/main-window.js

Update thumbnail after each sketch pane drawing operation.
Composite to a thumbnail from in-memory canvases
Save to a file
Load the file as an image
NOTE: still runs synchronously

Update thumbnails immediately

---

src/js/files/forked-file-writer.js
src/js/utils/canvas-buffer-ouput-file.js
src/js/utils/canvas-buffer-ouput-gif.js
src/js/utils/canvas-buffer.js
src/js/window/main-window.js

In trying to keep acceptable performance while drawing, the best way that I've found so far is to copy the canvas into a buffer, postponing any converstion and file writing until no drawing is happening. The new CanvasBuffer object, and its output strategies help manage this.
GH-387

Basic implementation of canvas recording.

---

src/js/window/main-window.js
src/js/window/welcome-window.js

If a storyboarder file is one of the files dropped, opening the project takes precedence, i.e. all other files are ignored.
Closes GH-366

Handle dropped files to the welcome and main windows. 

---

src/css/mainwindow.css
src/js/window/main-window.js

`updateBoardUI` returns a promise so we can wait until actually ready before showing the window.
Still has timeouts until we fix a resize bug #440.

Wait until ready before showing main window

---

src/js/window/color-picker.js
src/js/window/pomodoro-timer-view.js
src/js/window/tooltips.js

Fixes https://github.com/wonderunit/storyboarder/issues/497

Prevent Tooltips from showing if Sprint Sketch or Color Picker are active

---

src/js/window/main-window.js

Fixes #437 
Sets an upper limit for character count of the displayed filename. Does not update dynamically with window width yet. Using HTML title for tooltip.

Truncate right sidebar filename

---

src/js/main.js
src/js/window/main-window.js

In script-based projects, when switching to a scene, the first board was not initialized.
The thumbnail drawer tried to render an empty board list.
Caused errors like:
```
Uncaught TypeError: Cannot read property 'classList' of null
In file: […]/storyboarder/src/js/window/main-window.js#1811:74
```
```
Uncaught TypeError: Cannot read property 'url' of undefined
In file: […]/storyboarder/src/js/window/main-window.js#1292:22
```
Also fixed an issue with the script-based project title in the loading screen.
Fixes #675, #685

Fountain import fixes

---

package-lock.json
package.json
src/js/exporters/cleanup.js
src/js/files/file-helper.js
src/js/main.js
src/js/models/board.js
src/js/window/main-window.js
src/js/window/onion-skin.js
src/js/window/storyboarder-sketch-pane.js
test/exporters/cleanup.test.js
test/fixtures/ducks/ducks.storyboarder

Storyboarder should know what source file is linked per board (e.g.: file path to PSD).
- - [x] If artist agrees to continue after the warning, remove linkage in JSON. PSD file remains on filesystem until cleanup task is run.
To test:
If a user has a linked PSD open in Photoshop, closes Storyboarder and re-opens, and then re-saves the (still open) PSD, it won't update in Storyboarder. We could begin watching all links _when Storyboarder opens a project_, but we're not doing that yet. For now, you'll have to notice that it's not updating and choose "Open in Photoshop" again.
Fixes #654
---
FUTURE
- We only break the link on `pointerdown`. Would be better to break the link on _any_ activity that might change the canvas (e.g.: flip, paste)

Each board can have a "link" to a source file from an editor (e.g.: PSD)

---

src/js/window/main-window.js

Fix bugs related to missing images

---

src/js/window/main-window.js

Stores a key in memory, per thumbnail, and updates key when the watcher indicates a change. Uses key as cache buster when loading image. Default key is 0 (no change since first loaded).
Fixes #739

Ensure thumbnails update when thumbnail files change

---

src/js/main.js

If user is on Mac, and we're not in development mode, always prompt to move to Applications folder
Needs testing once built.
Closes #755

Prompt user to move app to Applications folder

---

package-lock.json
package.json
src/css/preferences.css
src/js/main.js
src/js/prefs.js
src/js/window/main-window.js
src/preferences.html

- For all active linked PSDs (where artist has, during this session, clicked the "Edit in Photoshop" button)...
- ... when the main workspace window receives focus
- ... copy layer images to the respective board from the source PSD

Reload from linked PSD(s) when window receives focus

---

src/js/files/file-helper.js
src/js/window/main-window.js

Image import had some bugs
- If image couldn't be loaded, blank board was created anyway
- If filename extension was 'jpeg', JPG was not loaded
This refactors the code to fix up a few cases and make the logic a bit more clear overall.
PSD import works, but currently requires a layer named `reference` to be present in the PSD, which is the only layer that will be imported.

Fix bug where blank board was created when trying to import an image

---

src/js/sketch-pane/index.js
src/js/window/onion-skin.js

Fixes a bug that prevented onion skin from loading images.

Fix Onion Skin

---

src/js/undo-stack.js
src/js/window/main-window.js
src/js/window/storyboarder-sketch-pane.js

NOTE we're still putting pixels to a canvas before uploading the redo state back to the GPU. This is slow. Would be better to write the pixels directly to a WebGL texture. Something we can fix in the future.
See Also:
https://github.com/pixijs/pixi-gl-core/blob/master/src/GLTexture.js#L323
https://github.com/mrdoob/three.js/issues/386#issuecomment-1681158
PIXI v5 texture-resource

New Sketchpane: Undo/Redo Performance Improvements

---

src/js/window/main-window.js
src/js/window/storyboarder-sketch-pane.js

I don't love the way we're exporting Util (for `arrayPostDivide` and `pixelsToCanvas`) but this will work for now.

Use the typescript build of Alchemancy

---

src/js/window/main-window.js

Better PSD sync: clear unused layers

---

src/js/main.js

If a keymap was created by 1.5.x, it will map tools to the wrong keys.
When we open it in 1.6.x, we can detect this, and fix it automatically.
Note that if the artist does open 1.5.x again, the keys will be unexpected.
Scenarios to test:
Fixes https://github.com/wonderunit/storyboarder/issues/1240

Force update from keymap 1.5.x to 1.6.x format

---

src/css/context-menu.css
src/js/window/color-picker.js
src/js/window/context-menu.js
src/js/window/pomodoro-timer-view.js

Overlapping `div` elements were causing WebGL slow-downs. This change sets `visiblity: false` on them when not in use.

Improvements for WebGL performance

---

src/js/main.js
src/js/menu.js
src/js/shared/helpers/defaultKeyMap.js
src/js/window/main-window.js

Adds two new commands
**File > Import Image to Current Reference Layer …**
- Selected PNG/JPG will replace reference layer of _current_ board, leaving metadata in tact
- PSD is not supported for this feature
**Edit >Paste and Replace Current (Image Only) …**
- Pasting layers (from another board) replaces all layers
- Pasting a single image (from system clipboard) replaces current reference layer
- Pasting a file (from system clipboard) replaces current reference layer)
- Pasting multiple files will just select the first one in the list and use it to replace current reference layer
- Pasting a PSD (from system clipboard) will replace current reference layer with flattened contents (test: is this full resolution? or from a small-resolution psd preview?)
- audio is not copied over
- linked …

"Import and Replace" / "Paste and Replace"

---

src/js/shared/reducers/shot-generator.js
src/js/shot-generator/Editor.js
test/shot-generator/reducers.test.main.js

Re-calculate `displayName` property of every scene object on the following actions:
- LOAD_SCENE
- CREATE_OBJECT
- DELETE_OBJECT
- DUPLICATE_OBJECT

Shot Generator: calculate displayName property of scene object on some scene changes

---

src/js/windows/shot-generator/main.js

This only works during a session. Once you close the app, the window position and size are forgotten.
I'll add some code in the future to persist the values to disk, and load them back for new sessions.

Shot Generator: remember window position and size during a session

---

src/js/shot-generator/BonesHelper.js
src/js/shot-generator/Character.js

BonesHelper generates a clone of the character object (skinned mesh + armature), which is expensive. This PR caches that clone per model type so it can be re-used.
Related to #1602

Shot Generator: in BonesHelper, cache clone per model type

---

src/js/window/main-window.js
src/js/windows/shot-generator/window.js

saves shots to `board.sg`
loads shots from `board.sg`
old data in `board.sts` is ignored

Shot Generator 2.0: save shot generator data to .sg instead of .sts

---

src/js/shot-generator/Volumetric.js

- fixed the bug where Shot Generator would load double the number of images when on a volume when opened from a storyboarder scene

Shot Generator 2.0: Volume double images fix

---

package-lock.json
package.json
src/js/shared/reducers/shot-generator.js
src/js/shared/reducers/shot-generator/batchGroupBy.js
src/js/shot-generator/Character.js
src/js/shot-generator/Editor.js
src/js/shot-generator/MultiSelectionInspector.js
src/js/shot-generator/NumberSlider.js
src/js/shot-generator/SelectionManager.js
src/js/shot-generator/SelectionsMover.js
src/js/windows/shot-generator/window.js
test/shot-generator/reducers.test.main.js

Artists expect that if they make a mistake, they can undo their changes, or redo.
We mainly care about the ability to undo changes to the scene objects (models, characters, lights, volumes), and mainly commonly used stuff like:
- position
- scale
- skeleton
- pose preset
For slider changes, we get many repeated action events in a row, firing many state changes. But we only care about the initial state when the slider started moving, to undo back to that state. (Look into [redux-undo’s `groupBy` feature](https://github.com/omnidan/redux-undo#grouping-actions))
UNDOABLE REDUCERS:
Test: create a new character, select it, then undo the create. Probably need to undo the select first as well to avoid having an undefined selection?
TASKS
---
---

Shot Generator 2.0: Undo/Redo

---

src/js/window/main-window.js

Ensures that, when Storyboarder first loads a scene, it always verifies the scene content _first_, and _then_ renders it.
During verification, it checks for missing linked PSD files, removes links, and notifies the user.
Fixes #1702

Handle missing linked PSD files

---

src/js/shared/reducers/shot-generator.js
src/js/shot-generator/Components.js
src/js/shot-generator/Editor.js

When a character preset is created or selected, use the character preset name as the character’s name.
Closes #1570

Set Character name to match Character Preset name

---

src/js/express-xr/src/SceneManagerXR.js
src/js/express-xr/src/components/SGWorld.js
src/js/shot-generator/World.js
src/js/shot-generator/only-of-types.js

- Filters out any objects that we don't support from the model data file.
- Then, adds all remaining meshes _and groups of meshes_ (instead of just the first level of children) to the scene
Fixes #1716

Load all meshes when importing an environment model

---

src/js/window/layers-editor.js
src/js/window/main-window.js
src/js/window/storyboarder-sketch-pane.js

- reference layer slider value is remembered<sup>*</sup>
- default opacity is 75%
- if you set the opacity to 0% and start drawing on the reference layer, it jumps to 75% so you can see what you're drawing
- any time you save a shot generator shot, it’s forced to 100%
Fixes #1116
<b id="f1">*</b> <i>as long as you have either a reference layer drawing or a shot generator shot. if you've never drawn on the reference layer or added a shot generator shot, and you set the value, we don't have any layer data to store it on, so it is not remembered. you must draw or add a shot to store it.</i>

Use reference layer opacity slider for shot generator layer also

---

package.json
src/js/shot-generator/Character.js
src/js/shot-generator/Components.js
src/js/shot-generator/PosePresetsEditor.js
src/js/shot-generator/World.js
src/js/vendor/three/examples/js/loaders/GLTFLoader.js
src/js/vendor/three/examples/js/utils/SkeletonUtils.js

- vendor r107 versions of three/example files (`GLTFLoader` and `SkeletonUtil`) so Shot Generator can find them
- specifically exclude `scripts/` from the built app
- specifically exclude `dist/` from the built app (although probably not needed, as electron-builder does this already)

Build process improvements

---

src/js/shared/IK/IkHelper.js
src/js/shared/IK/SGIkHelper.js
src/js/shared/IK/objects/IkObjects/Ragdoll.js
src/js/shot-generator/Character.js

Implemented saving of changed pole targets position in VR and applying them to SG.
Old boards with changed pole targets position will have their positions in a different place than before because the way of saving pole targets position has changed. Simply move them to a new position.

Saving Pole Targets position across Xr and SG

---

src/js/shot-generator/Character.js

Fixed the inability to rotate bones when a non-initial camera is selected

Fixed second camera can't rotate bones

---

src/js/shot-generator/ModelSelect.js

When switching between objects, sometimes incorrect values are displayed in the left pane

inspector info fix

---

src/js/shot-generator-new/components/SelectionManager/index.js

Fixed minor SelectionManager bugs such as:
1. Cannot deselect multiple selected object 
2. Holding click and releasing on character throws an error

Fixed cannot select whole group and deselect on empty space click

---

src/css/shot-generator.css
src/js/shot-generator/components/InspectedElement/GeneralInspector/Volume.js
src/js/shot-generator/components/Select/index.js

Volume Select currently shows the entire relative path as the Select label:
This PR changes it to be somewhat more legible:
Would be nice to also reduce the font size, and fix the focus outline (which is clipped and only shows blue on the left of the input), but not necessary for now.
/cc @VladStepura

Volume: show file names for custom images

---

src/js/menu.js

Frequently we’ll ask for the log file when troubleshooting. This would help users locate it quickly.

Add “Show Log File…” to Help menu

---

src/js/window/main-window.js

Allow missing files. If there are any files missing, show a notification.
Allow missing files. If there are any files missing, warn with a modal dialog before loading the new copy.
Fixes #1155

Allow missing files for “Save As” and ”Export Project as ZIP”

---

src/js/exporters/ffmpeg.js

The video export doesn't work in the new release. #2107 
The file path for FFmpeg doesn't replaced properly. In the previous version of the storyboard, [Electron-utils](https://github.com/wonderunit/storyboarder/blob/efb823cd79303819c4c4ad691b6b6d341e868e03/src/js/exporters/ffmpeg.js#L12) was solving for file path change, but with the change of electron version, the way mainModule behave changed and the Electron-utils doesn't take this into consideration.
FFmpeg file path is manually changed from "app.asar" to "app.asar.unpacked" on the FFmpeg export

Fix for video export

---

src/js/shared/IK/objects/ObjectRotationControl.js
src/js/shot-generator/components/Three/Character.js
src/js/shot-generator/components/Three/InteractionManager.js
src/js/shot-generator/hooks/use-dragging-manager.js

Moves the rotation gizmo to top of the character and adds rotation podium for character
Moving rotation gizmo seems logical cause most of the time you spend zoomed at the character top part and having gizmo at the top significantly simplify character adjusting. 
Character's rotation podium is an ability to rotate character on ctrl + dragging. It's an alternative way to rotate a character.

Character Rotation

---

src/js/shot-generator/components/Three/Environment.js
src/js/shot-generator/helpers/GrayscaleFragmentShader.js
src/js/xr/src/components/Environment.js

The environment texture is black.
The grayscale needs to be brighter.
Overriding of material for the environment sets the flat shading to false by default. The flatshaded environments require that flat shading of material set to true.
Added copying of original material flat shading state to overriding material.
Increased grayscale brightness.

Fixed flatshaded environments

---

src/js/window/main-window.js
src/js/window/tooltips.js

Tooltips in storyboarder don't change the description on language change.
The tooltips initialized only once and stored, so the language change doesn't affect them.
The solution is to recreate the tooltips on language change.

Storyboarder: tooltips don't change on language change

---

package-lock.json
package.json
src/js/services/server/sockets.js
src/js/shared/network/peerUtils.js
test/xr/sockets.renderer.test.js

Makes `resolvePublicPath` its own function that can be tested independently.
Simplifies the list of public directories as `getPublicDirectories`

https-server: extract resolvePublicPath from getResource

---

src/js/locales/en-US.json
src/js/shared/actions/scene-object-creators.js
src/js/shot-generator/components/Toolbar/index.js
src/js/shot-generator/hooks/use-insert-image.js
src/js/shot-generator/services/filepaths.js
test/shot-generator/services/filepaths.renderer.test.js

Ability to insert an image into shot-generator either thought clipboard or drag and drop file
Inserting an image from the clipboard creates the new image file with generated id. Inserting image by drag and drop copies image from path, a potential problem might occur in [image-drawing](https://github.com/wonderunit/storyboarder/pull/2011) branch when multiple images reference the same file

Shot-generator image insertion

---

src/js/shot-generator/CameraControls.js

After pressing keys down in Shot-Generator and unfocusing the window(selecting other windows) the key remains pressed
The key up event doesn't fire the window is unfocused leading to keydown remaining pressed
The solution is to add onBlur event which resets all downed keys

Fixed keydown locks on window blur

---

src/js/services/server/sockets.js
src/js/shared/network/client.js
src/js/shared/reducers/shot-generator.js
src/js/shot-generator/components/Three/InteractionManager.js
src/js/shot-generator/helpers/outlineMaterial.js
src/js/xr/src/SceneManagerXR.js
src/js/xr/src/use-interactions-manager.js

The idea was to block an object only when the user drags it, not on select.
Blocking dragging object prevents a bug situation when a few users try to drag it at the same time.

Blocking on drag
