wonderunit/storyboarder

src/css/mainwindow.css, src/js/main.js, src/js/menu.js, src/js/window/main-window.js, src/js/wonderunit-utils.js, src/main-window.html
Completed
Remaining
Enhancements
Fixes #28
=> User can operate on multiple boards at a time (WIP)

src/js/window/main-window.js
Fixes https://github.com/setpixel/storyboarder/issues/62
=> Redraw only selections in thumbnail drawer, when appropriate

src/js/main.js
I've been referencing this hack all the time in development. Is this a good idea?
=> Obvious Debug Mode

src/js/main.js, src/js/menu.js, src/js/utils/index.js, src/js/window/main-window.js
Closes https://github.com/setpixel/storyboarder/issues/72
Known issue: https://github.com/setpixel/storyboarder/issues/83
=> Re-order Left/Right

src/js/window/main-window.js
=> Update selection and currentBoard in moveSelectedBoards

src/css/transport.css, src/img/button-pause.svg, src/img/button-play-pause.svg, src/img/button-play.svg, src/js/menu.js, src/js/window/main-window.js, src/js/window/transport.js, src/main-window.html
=> Add Transport controls

DEVELOPERS.md, src/js/main.js, src/js/menu.js, src/js/window/main-window.js
Clean up view mode cycling (vs toggling).
Clean up some key handling while input fields are focused.
Let devs know what node version they should be using.
=> Clean up cycle view mode

src/css/mainwindow.css, src/css/toolbar.css, src/main-window.html
Scrollable sidebar.
Adds a slight gradient fade underneath to indicate scrolling is available.
=> Responsive Metadata sidebar

src/js/window/guides.js, test/views/guides/index.html
Draw white, followed by black, for guide lines.
=> Guide Colors

src/js/window/main-window.js, src/js/window/toolbar.js
Kind of messy. As a future refactoring, the color palette could become its own component.
Fixes #122
=> Connect Color Picker control to Color Palette swatches

src/css/toolbar.css, src/js/sketchpane.js, src/js/window/main-window.js, src/js/window/toolbar.js, src/main-window.html
=> User can see Brush Size in Toolbar

src/css/toolbar.css, src/js/window/main-window.js
- on window resize, set reduced width class for toolbar
Fixes #127
=> Simplified Toolbar at smaller display widths

src/js/storyboarder-sketch-pane.js, src/js/undo-stack.js, src/js/window/main-window.js
=> Layers: Multi-Layer Eraser

package.json, src/js/window/main-window.js
Basic implementation of #202 
Clicking "Open in Editor" now generates a layered photoshop file, sends the system command to open it, and then watches for updates to the file. When the file has been updated, we open up the file, iterate through it's layers ignoring those named "notes" or "reference", then draw those back into the main layer canvas.
=> Edit in Photoshop

src/js/main.js, src/js/menu.js, src/js/window/main-window.js
=> added save button to menu and command s accel

src/css/preferences.css, src/js/main.js, src/js/prefs.js, src/js/window/main-window.js, src/js/windows/preferences/editor.js, src/preferences.html
=> Add preference for defaultBoardTiming

src/js/window/main-window.js
Images will be imported to a new board.
Closes #328
=> User can trigger an import to new board via context menu

src/js/files/FileReader.js, src/js/main.js, src/js/menu.js, src/js/window/main-window.js
This pull requests includes the following:
#332 - Make an accelerator key for editing a board in photoshop
#333 - Add a notification after images import
#334 - when editing in photoshop use the board's UID for the filename
#338 - Add a white background layer in exported PSD
=> Photoshop and Importing Improvements

src/css/keycommand-window.css, src/js/main.js, src/js/menu.js, src/js/window/keycommand-window.js, src/keycommand-window.html
=> 166 key command cheatsheet

package-lock.json, package.json, src/js/exporters/common.js, src/js/exporters/final-cut-pro.js, test/exporters/common.test.js, test/exporters/final-cut-pro-x.test.js, test/exporters/final-cut-pro.test.js
- Better tests
- Better docs
- Fix error handling for when image doesn't load during export
=> Thumbnail generator enhancements

src/js/window/main-window.js
=> Save image (and ensure layer data exists) before saving project data

src/js/exporters/common.js, src/js/files/FileReader.js, src/js/window/main-window.js
Use more of the common exporter fns
Fix some bugs
=> Refactor "Paste Board(s)

src/js/window/main-window.js
=> Duplicate Board via file copy

src/js/window/main-window.js, src/js/window/toolbar.js, src/main-window.html
=> Move "Edit in Photoshop" to top nav

src/css/mainwindow.css, src/import-window.html, src/js/main.js, src/keycommand-window.html, src/new.html, src/print-window.html, src/welcome.html
Also adds titles for the other windows.
Closes #255
=> Show Filename in UI (title bar, footer/right side stats)

src/js/exporters/common.js, src/js/window/main-window.js, src/js/window/storyboarder-sketch-pane.js
=> Don't save thumbnail immediately after drawing

src/css/preferences.css, src/js/prefs.js, src/js/sketch-pane/index.js, src/preferences.html
=> Added a preference for toggling painting canvas opacity during drawing.

src/js/prefs.js, src/js/window/storyboarder-sketch-pane.js, src/preferences.html
Disabling this enhances performance.
GH-405
=> Added a preference to toggle a brush cursor in the sketch pane. 

src/js/window/main-window.js
Waits 500 msecs after drawing before updating stats.
Fixes #419
=> Only update stats when idle

src/js/prefs.js, src/js/window/main-window.js, src/js/wonderunit-sound.js, src/preferences.html
(Until we optimize it more for performance).
Don't add the sonifier's listeners if the preference is disabled.
GH-404
=> Disable sonifier by default

src/js/exporters/common.js, src/js/window/exporter.js, src/js/window/main-window.js
=> flattened animated gif + captions + 888 width

src/css/toolbar.css, src/js/window/main-window.js
=> Toolbar Tweaks

src/js/utils/canvas-buffer.js, src/js/utils/canvas-recorder.js, src/js/window/main-window.js
Encapsulates the recording and output of canvas recordings.
GH-387
=> Added CanvasRecorder

src/js/window/storyboarder-sketch-pane.js
=> Eraser tool should not change the apparent opacity of layers

src/js/window/layers-editor.js, src/js/window/main-window.js, src/main-window.html
Bundle o' fixes re: reference layer.
- Reference layer can be hidden (0% opaque) #459
- Show reference layer while drawing if hidden #465 
- Render thumbnail with consistent opacity for reference layer #460
AKA light layer
=> Improvements to Reference Layer

src/css/mainwindow.css
=> Sidebar min size of 300px

src/js/main.js, src/js/utils/index.js, src/js/window/main-window.js, src/loading-status.html, test/util/util.test.js
=> Show status while loading a project

src/js/main.js, src/js/window/new-window.js, src/new.html
Tasks:
Testing:
- Create a new project from an existing script
- Try to create a new new project but select a script that has _already_ been converted into a project
- Use `File > Open` to select a script
- Create a new Blank project at each aspect ratio
- Create a new Blank project but select a folder that _already_ exists
- Create a new Blank project but select a `.storyboarder` that _already_ exists
=> “Select Aspect Ratio” Window

src/js/exporters/common.js, src/js/window/layers-editor.js, src/js/window/main-window.js
=> consistent default reference layer opacity

src/js/window/main-window.js
=> Support changing eraser size with keys during Quick Erase mode

src/js/files/file-helper.js, src/js/window/main-window.js
=> Support for opening multiple frames as Photoshop documents.

src/js/main.js, src/main-window.html
In dev mode, we also pop open the dev tools with the full error trace
=> Main Window Errors: always display error message, always log to analytics

src/js/window/color-picker.js, src/js/window/context-menu.js
=> Added a cancelable delay for closing the thumbnail context menu and color picker

src/js/express-app/app.js, src/js/express-app/index.html, src/js/express-app/public/js/main.js, src/js/main.js
=> Worksheet Upload via Server

src/import-window.html, src/js/window/import-window.js, src/js/window/welcome-window.js
=> Corner Points Editor

package-lock.json, package.json, src/import-window.html, src/js/window/import-window.js
Fixes #510 
Updates `electron` to `1.7.5`, requires `npm install`.
=> Prompt user to enter the QR code if none found

src/js/window/import-window.js
=> Allow manual tweaking of corner points

package.json, src/js/prefs.js, src/js/window/import-window.js
=> Worksheet Import: offsets are now loaded from, and saved to, prefs

src/js/express-app/app.js, src/js/express-app/index.html, src/js/express-app/public/js/main.js, src/js/main.js
=> Web Remote: Prevent importing when project is not available

src/css/print-window.css, src/import-window.html, src/js/main.js, src/js/window/main-window.js, src/js/window/print-window.js, src/print-window.html
=> Print Worksheet: can export a printable PDF

src/css/preferences.css, src/js/window/storyboarder-sketch-pane.js, src/preferences.html
=> Fix bug where disabling brush cursor caused an error

src/js/constants.js, src/js/exporters/common.js, src/js/window/layers-editor.js, src/js/window/main-window.js, src/js/window/storyboarder-sketch-pane.js
=> Remember reference layer’s opacity

src/js/window/main-window.js, src/js/window/toolbar.js
=> Thumbnail bug fixes

src/import-window.html, src/js/prefs.js, src/js/window/import-window.js
=> Worksheet Import: Optional "skip blank boards"

src/import-window.html, src/js/prefs.js, src/js/window/import-window.js
=> Worksheet Import: Remember last-used QR code

src/js/window/main-window.js, src/js/window/sts-sidebar.js
=> Reset tooltips when STS selects change

src/js/menu.js, src/js/window/main-window.js, src/js/window/welcome-window.js
Needs to be tested on Windows. Check Welcome Window and Main Window (Project Workspace)
Related to #595
=> Application Menu Fixes

src/js/prefs.js
=> Default to no sound

src/js/shot-template-system/index.js, src/js/window/main-window.js, src/js/window/toolbar.js
=> Disable WebGL features when WebGL is not present

src/js/windows/preferences/index.js
=> Preferences: on window request, focus if already open

src/js/window/main-window.js
=> Fix bug where undo caused errors in some cases

src/js/menu.js, src/js/window/keycommand-window.js, src/js/window/main-window.js
=> Shift+Tab cycles view modes in reverse

src/js/main.js, src/js/window/main-window.js, src/loading-status.html
Closes https://github.com/wonderunit/storyboarder/issues/706
Closes https://github.com/wonderunit/storyboarder/issues/719
=> Fountain scripts: better error handling while loading

src/js/window/main-window.js
=> Re-create missing files

src/js/window/main-window.js
=> Force reload after cleanup

src/js/window/main-window.js
=> On playback, wait for board data to update before reading duration

package-lock.json, package.json, src/js/exporters/archive.js, src/js/main.js, src/js/menu.js, src/js/window/main-window.js, test/exporters/archive.test.js
=> Artist can export Project as a ZIP file

src/js/window/import-window.js
Allows us to support rotated images.
Fixes #702
=> Don’t sort Corner Points if entered manually

src/js/main.js, src/js/window/main-window.js, test/importers/fountain-scene-id-util.test.js
=> Watch .fountain script file and reload if it changes

src/js/exporters/final-cut-pro-x.js, src/js/exporters/final-cut-pro.js, src/js/utils/index.js, src/js/window/exporter.js, test/exporters/final-cut-pro-x.test.js, test/exporters/final-cut-pro.test.js, test/util/util.test.js
=> FCP(X)/Premiere export: replaces spaces with dashes in asset file names

src/js/window/main-window.js
=> Copy and Paste copies linked PSD

src/js/window/layers-editor.js, src/js/window/main-window.js, src/js/window/storyboarder-sketch-pane.js
=> Lock linked boards

src/js/window/main-window.js
=> Only notify on re-order if order actually changes

src/css/mainwindow.css, src/js/window/main-window.js
=> Remove scrolling animation on drawer when switching boards

src/js/window/main-window.js
=> Draggable timeline

package-lock.json, package.json, src/js/exporters/final-cut-pro-x.js, src/js/exporters/final-cut-pro.js, src/js/main.js, src/js/prefs.js, src/js/window/main-window.js, src/js/window/scene-settings-view.js, src/main-window.html, test/exporters/final-cut-pro-x.test.js, test/exporters/final-cut-pro.test.js
=> Artist can set frame rate of scene

src/js/importers/final-draft.js, test/fixtures/final-draft/test.fdx
=> final cut import: fix bug when character paragraph's child text has attributes

src/css/mainwindow.css
https://www.facebook.com/groups/storyboarder/permalink/711305965739002/
=> More obvious color accent

package-lock.json, package.json, src/css/preferences.css, src/js/prefs.js, src/js/window/main-window.js, src/js/windows/preferences/editor.js, src/preferences.html, test/prefs.main.test.js, test/prefs.renderer.test.js
=> Artist can set a preference for PSD editor application

src/css/mainwindow.css, src/js/main.js, src/js/menu.js, src/js/window/audio-file-control-view.js, src/js/window/audio-playback.js, src/js/window/main-window.js, src/main-window.html
=> Audio Recording

package-lock.json, package.json, src/js/exporters/ffmpeg.js, src/js/main.js, src/js/menu.js, src/js/models/board.js, src/js/vendor/ext/tone-player-with-curve.js, src/js/window/audio-playback.js, src/js/window/exporter.js, src/js/window/main-window.js, test/exporters/ffmpeg.renderer.test.js
=> Video Export

src/js/vendor/ext/tone-player-with-curve.js
=> Fix bug where audio player would not stop

src/css/mainwindow.css, src/js/main.js, src/js/menu.js, src/js/models/board.js, src/js/models/scene.js, src/js/shared/helpers/defaultKeyMap.js, src/js/utils/index.js, src/js/window/main-window.js, src/js/window/scene-timeline-view.js, test/util/util.test.js
=> New Timeline

package-lock.json, package.json, src/css/upload.css, src/js/exporters/ffmpeg.js, src/js/exporters/web.js, src/js/main.js, src/js/menu.js, src/js/shared/reducers/index.js, src/js/utils/index.js, src/js/window/main-window.js, src/js/windows/preferences/editor.js, src/js/windows/upload.js, src/preferences.html, src/upload.html, test/exporters/web.renderer.test.js
Users can Export Scene to Web.
Exporter creates a web-compatible, network-friendly, smaller version of the current scene as a ZIP file.
Users (who have already registered on the site) can sign in from the app, and upload to the Storyboarders web service from the app.
=> Export Scene to Web

src/css/mainwindow.css, src/img/symbol-defs.svg, src/js/main.js, src/js/menu.js, src/js/window/main-window.js, src/js/window/sts-sidebar.js, src/main-window.html
=> Metadata Sidebar Discoverability

package-lock.json, package.json, src/js/exporters/cleanup.js, src/js/exporters/copy-project.js, src/js/exporters/web.js, src/js/main.js, src/js/models/board.js, src/js/window/main-window.js, src/js/window/onion-skin.js, src/js/window/storyboarder-sketch-pane.js, test/exporters/cleanup.test.js, test/exporters/copy-project.test.js
=> Add Posterframes

src/js/prefs.js, src/js/window/diagnostics-view.js, src/js/window/main-window.js, src/preferences.html
Closes https://github.com/wonderunit/storyboarder/issues/1129
=> Add "Enable Diagnostics" to Preferences UI

src/js/window/main-window.js, src/js/window/storyboarder-sketch-pane.js
Closes https://github.com/wonderunit/storyboarder/issues/1125
=> Basic Canvas Recorder integration with new SketchPane

package.json, src/js/exporters/copy-project.js, src/js/window/main-window.js, test/exporters/copy-project.test.js
=> Backup scenes before migrating

src/js/window/main-window.js
=> Warn if backup of a scene is opened

src/js/window/main-window.js, src/js/windows/preferences/editor.js, src/js/windows/preferences/index.js
=> Notify on Preference Change

package-lock.json, package.json, src/css/toolbar.css, src/css/tooltip.css, src/js/shared/reducers/preferences.js, src/js/shared/reducers/toolbar.js, src/js/window/storyboarder-sketch-pane.js, src/js/window/toolbar.js, src/main-window.html, test/preferences.renderer.test.js
requires new alchemancy
needs a quick review for how it writes to prefs
=> Add “Stroke Opacity” control

package-lock.json, package.json, src/js/main.js, src/js/menu.js, src/js/shared/helpers/defaultKeyMap.js, src/js/shared/reducers/toolbar.js, src/js/utils/keytracker.js, src/js/window/main-window.js, src/js/window/storyboarder-sketch-pane.js
=> Add Zoom and Pan

src/js/main.js
=> Save keymap on change

src/js/menu.js
=> Fix Edit > Preferences for Linux

src/js/window/main-window.js
=> don't automatically saveImageFile during clearLayers

src/js/window/storyboarder-sketch-pane.js
=> Use "grab" cursor while panning

src/js/window/exporter.js, src/js/window/print-window.js
=> Use posterframes for PDF export

src/js/window/main-window.js
=> Generate missing posterframes on window load

src/js/window/main-window.js
=> save to backup, then swap, to avoid corrupting .storyboarder file

src/js/window/audio-file-control-view.js, test/exporters/cleanup.test.js, test/exporters/copy-project.test.js
=> Buffer.from

src/js/window/storyboarder-sketch-pane.js
=> scale offset by actual scale on screen, not user zoom level

src/js/window/main-window.js, src/js/window/storyboarder-sketch-pane.js
=> Alert and force quit if WebGL context is lost

src/css/update.css, src/js/auto-updater.js
Needs testing
Related to #1393
=> Descriptive error messages for auto update

src/js/shot-generator/BonesHelper.js, src/js/shot-generator/Character.js, src/js/shot-generator/DragControls.js, src/js/shot-generator/Editor.js, src/js/windows/shot-generator/main.js
- bones flat shading
- youth male standard material fix
- outline on same character model fixed
=> added back material changes and fixes from shot-generator branch

src/js/shot-generator/Editor.js
- TO DO: update correct values when new character added
=> Shot generator distances to closest character

src/js/shot-generator/Character.js
=> Shot Generator 2.0: Fix model issues

src/js/shot-generator/Editor.js
Only dispatch an `UPDATE_OBJECT` event if values have changed.
=> Shot Generator 2.0: Fix camera update dispatch frequency

src/css/shot-generator.css, src/js/shot-generator/Editor.js, src/js/shot-generator/ServerInspector.js
- ServerInspector to display QR code for server
- basic CSS
- animate in
=> Shot Generator 2.0: QR code

src/js/main.js, src/js/shared/reducers/shot-generator.js, src/js/shot-generator/Editor.js, src/js/window/main-window.js, src/js/windows/shot-generator/window.js
=> Shot Generator 2.0: Save (by board uid) and Insert (after current board)

src/js/shot-generator/Character.js, src/js/shot-generator/Editor.js
=> Shot Generator: Rendered image should exclude helpers (#1550)

src/js/services/model-loader.js, src/js/shot-generator/Character.js, src/js/shot-generator/SceneObject.js
=> Shot Generator: Prompt to locate missing model files

package-lock.json, package.json, src/js/main.js, src/js/services/model-loader.js, src/js/shared/reducers/shot-generator.js, src/js/shot-generator/Character.js, src/js/shot-generator/Editor.js, src/js/shot-generator/SceneObject.js, src/js/shot-generator/World.js, src/js/shot-generator/prepare-filepath-for-model.js, src/js/window/main-window.js, src/js/windows/shot-generator/window.js, test/shot-generator/model-loader.test.main.js
Fixes #1563, https://github.com/wonderunit/storyboarder/issues/1577
=> Shot Generator: Copy Model Files

src/js/shot-generator/Character.js, src/js/shot-generator/Editor.js
see details in the commit comment: https://github.com/wonderunit/storyboarder/pull/1584/commits/1d8d08e100d4b896008016d56222dbb29db8f975
=> Shot Generator: Reset Character skeleton pose if the board uid changes

src/css/shot-generator.css, src/js/menu.js, src/js/shared/reducers/shot-generator-presets/poses.json, src/js/shot-generator/Editor.js, src/js/shot-generator/PosePresetsEditor.js, src/js/vendor/three/examples/js/utils/SkeletonUtils.js
=> Shot Generator 2.0: Pose Preset Selector UI

src/js/shared/reducers/shot-generator.js, src/js/shot-generator/Editor.js, src/js/shot-generator/World.js, src/js/shot-generator/build-square-room.js, test/fixtures/shot-generator/shot-generator.storyboarder
- Ground disappears if Room is present
- Metric base unit for Room
=> Scene Generator 2.0: Room Improvements

src/js/shot-generator/Editor.js, src/js/shot-generator/PosePresetsEditor.js
todo: test that saving to json still works
=> Shot generator pose presets editor performance

src/js/shared/reducers/shot-generator.js, src/js/shot-generator/CameraControls.js, src/js/shot-generator/Components.js, src/js/shot-generator/Editor.js, src/js/shot-generator/SceneManager.js
=> Shot Generator: Undo fixes

src/js/window/linked-file-manager.js, src/js/window/main-window.js
=> Linked PSD: read from PSD when focused

package-lock.json, package.json, src/js/express-xr/src/SceneManagerXR.js, src/js/express-xr/src/gui/GUI.js, src/js/express-xr/src/index.html, src/js/express-xr/src/lib/VRController.js
Allow controllers to be connected/disconnected
TASKS
=> Shot Generator VR: controller fix

src/js/shot-generator/PosePresetsEditor.js
=> Shot Generator 2.0: pose preset json fix

src/js/shot-generator/Character.js
=> Shot Generator 2.0: Fix unexpected character rotation

package-lock.json, package.json, src/js/exporters/copy-project.js, src/js/models/shot-generator-data.js, test/exporters/copy-project.test.js
=> Shot Generator 2.0: export models folder

src/js/express-xr/src/SceneManagerXR.js
BUG: You can't select an object/character with the grip anymore
while dragging, if holding the second trigger
snap y rotation to 22.5
set x rotation to 0
set z rotation to 0
=> XR Controller Tweaks

src/js/shot-generator/Components.js, src/js/shot-generator/Editor.js, src/js/window/notifications.js, src/shot-generator.html
=> non-blocking “Open in VR” dialog

src/js/utils/sortFilePaths.js, src/js/window/main-window.js, test/util/sortFilePaths.test.main.js
=> Sort filenames of imported image files numerically

src/css/shot-generator.css, src/js/shot-generator/Editor.js, src/js/shot-generator/FatalErrorBoundary.js
=> Report fatal errors to user

src/js/express-xr/src/SceneManagerXR.js, src/js/express-xr/src/components/SGCharacter.js, src/js/express-xr/src/components/SGVirtualCamera.js, src/js/express-xr/src/gui/GUI.js, src/js/express-xr/src/hooks/useAttachmentLoader.js, src/js/express-xr/src/utils/xrControllerFuncs.js, src/js/express-xr/src/utils/xrHelperFuncs.js, src/js/express-xr/src/utils/xrObjectSettings.js
SceneManagerXR code refactor
BUG boxes with different sizes in constrain mode change size
BUG morph targets not set when loading characters
BUG: character name missing in inspector
FIX: properties not consistent for object (min max: width height and depth of a box are wrong )
BUG: disable slider when dragging or selecting
FEATURE: add a border around the virtual camera view (but not a box, a mesh border)
=> XR Refactor and bug fixes

src/js/window/main-window.js
=> Playback Sync

src/js/express-xr/src/SceneManagerXR.js, src/js/express-xr/src/components/SGCharacter.js, src/js/express-xr/src/components/SGModel.js, src/js/express-xr/src/components/SGSpotLight.js, src/js/express-xr/src/components/SGVirtualCamera.js, src/js/express-xr/src/utils/xrHelperFuncs.js
**FEATURE**: selected object should appear purple emissive
**MODIFICATION** - Flatten camera outline, color purple, purple camera
Adjust Virtual Camera materials
=> XR visual updates

src/js/express-xr/src/SceneManagerXR.js
Show "Loading…" while assets are prepared, then the "Enter Shot Generator VR" button once ready.
=> Shot Generator VR: preloader

src/js/express-xr/src/SceneManagerXR.js, src/js/express-xr/src/gui/GUI.js
Controllers don't have the initial lag anymore because most of the textures are preloaded in SceneManager
=> extracted selector-gui texture loading

src/js/shot-generator/SceneManager.js
=> Shot Generator: better resize behavior

src/js/express-xr/src/SceneManagerXR.js, src/js/express-xr/src/components/SGVirtualCamera.js, src/js/express-xr/src/gui/GUI.js, src/js/express-xr/src/gui/GUIElement.js
* Correct aspect ratio icons + titles for Selector
* GUI Camera no longer visible through everything
=> XR Selector Icons & Titles

src/js/xr/src/helpers/get-controller-intersections.js, src/js/xr/src/use-interactions-manager.js
=> XR: invisible bones still cause hover effect sound

src/js/shared/reducers/shot-generator.js, src/js/shot-generator/Components.js, src/js/shot-generator/NumberSlider.js, src/js/xr/src/SceneManagerXR.js
=> Fog params

src/js/vendor/three/examples/js/vr/WebVR.js, src/js/xr/src/SceneManagerXR.js
- merge changes from three r107 to vendor WebVR
- use vendor'd WebVR file
=> XR: style for "Enter Shot Generator VR" button

src/js/xr/src/components/Character.js, src/js/xr/src/three/IK/XrRagdoll.js, src/js/xr/src/three/IkHelper.js
Fixing:
1) If you grip one object and select another will through an error
2) End targets move when moving the hips around
3) The pole targets saved in the wrong order
=> Different fixes for ik in xr

src/js/shared/IK/SGIkHelper.js, src/js/shared/IK/objects/ControlTargetSelection.js, src/js/shared/IK/objects/IkObjects/IkObject.js, src/js/shared/IK/objects/IkObjects/Ragdoll.js, src/js/shared/IK/objects/TargetControl.js
Fixed `ik-refactor` and `ik-hips-rotation` after merge bugs.
Bugs:
1. Fixed rotation doesn't work
2. Pole targets visibility
3. Locking and unlocking rotation doesn't affect legs and head
=> Fixed bugs ik Merge bugs

src/js/xr/src/components/VirtualCamera.js
Removed some offset in xr virtual camera which moved a camera slightly forward
=> Fixed xr virtual camera offseted from sg camera

src/js/xr/src/hooks/use-vr-controllers.js, src/js/xr/src/use-interactions-manager.js
Added an ability to change your headset height aka going up and down. You can change your height by pressing the right thumbstick for going up and the left thumbstick - going down.
=> Xr Elevation Control

src/js/xr/src/use-interactions-manager.js
Fixed bug when you can pose character and press undo button which results in character disappearing from the scene and VR lock.
=> Fixed when posing character can press undo and redo

src/js/xr/src/hooks/ui-manager/index.js
Fixes bugs with the hand pose presets such as:
1. Inability to change box height, width and character's height 
2. While hand pose panel is active selecting a box will throw an error
=> Fixes for hand pose preset

src/js/shot-generator/World.js
Fixed bug where environment is outlined on the selection of object or character
=> Fixed environment is highlighted on object selection

src/js/shared/IK/XrRagdoll.js, src/js/shared/IK/objects/IkObjects/Ragdoll.js
Changed default position of pole targets to be near the hips
=> Xr pole targets fix

src/js/shot-generator-new/Components.js, src/js/shot-generator-new/components/CharacterPresetEditor/index.js
Refactored CharacterPresetEditor:
1. Extracted from components.js
2. Switched to jsx
=> Shot generator refactoring character preset

src/js/xr/server.js
=> Fixed xr paths

src/js/shot-generator-new/CameraControls.js, src/js/shot-generator-new/Character.js, src/js/shot-generator-new/SceneManager.js, src/js/shot-generator-new/components/InspectedElement/AttachableInspector/index.js, src/js/shot-generator-new/components/InspectedElement/BoneInspector/index.js, src/js/shot-generator-new/components/InspectedElement/GeneralInspector/Character.js, src/js/shot-generator-new/components/SelectionManager/index.js
1. Fixed validMorphTargets of undefined
2. Fixed cameraControls not updating it's positions
3. Fixed cannot add custom attachable
4. Fixed changing handPose revert headScale
5. Fixed pointerUp is firing in selectionManager without pointerDown
6. Fixed cannot control camera in small canvas
7. Fixed boneInspector returns null
=> Shot generator refactoring ui fixes

src/css/shot-generator.css
Fixes https://github.com/wonderunit/storyboarder/issues/1930
=> fix overflowing word from hiding remove button

src/css/shot-generator.css, src/js/shot-generator/SceneManagerR3fLarge.js, src/js/shot-generator/components/InspectedElement/GeneralInspector/Character.js, src/js/shot-generator/components/InspectedElement/GeneralInspector/Object.js
Added drop button to the object and character tabs. And fixed dropping objects and characters event if they are in a locked state
=> [WIP] Shot Generator drop button

src/css/shot-generator.css, src/js/shot-generator/components/InspectedElement/PosePresetsInspector/index.js
Added ability to mirror current character pose. Button for mirroring is placed in the character's pose tab.
=> [WIP] Shot Generator pose mirroring

src/js/shot-generator/SceneManagerR3fSmall.js, src/js/shot-generator/components/NumberSlider/index.js, src/js/shot-generator/components/Three/CameraControlsComponet.js, src/js/windows/shot-explorer/window.js, src/js/windows/shot-generator/window.js
Fixed numberslider's jumpinnes
Fixed topdown icon selection
=> [WIP] Shot Generator merge fixes

src/js/menu.js, src/js/shot-generator/components/Editor/index.js, src/js/windows/shot-generator/main.js, src/js/windows/shot-generator/settings.js
Implemented an ability to zoom up and down content(UI) in shot-generator. Saves zoom settings. Automatically zooms down for small resolution screens.
=> Shot-generator UI scale

src/js/shared/actions/scene-object-creators.js, src/js/shot-generator/components/Toolbar/index.js
Create light and volume object in front of a camera, works the same way as object creation;
Light supposed to always be in the air, so the light position is created at a constant height of 2
=> Objects Creation in Front of camera

src/js/shot-generator/components/Three/Character.js, src/js/utils/isSuitableForIk.js, src/js/xr/src/components/Character.js, src/js/xr/src/use-interactions-manager.js
The Pose capture in xr is offsetting the head control point.
The xr doesn't support ik for custom characters.
The pose capture used the wrong camera for character head offset.
The pose capture uses real camera instead of camera
For the ik support isSuitableForIk was added to xr
=> Xr Character fixes

src/js/shared/network/client.js, src/js/xr/src/use-interactions-manager.js
Problem: If you select a character, it will disable the UI on the controller.
PR fixes it.
=> blocking fix
